# -*- coding: utf-8 -*-
"""파워 유저를 위한 파이썬 - Chapter 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQ6Td-E8sePMGxH8R1oirkqDCPYHldaD
"""

# 1. 
for i in range(1, 51):
  if i%2 == 0:
    print(i, end = ',')

# 2. 
myList = [11, 22, 23, 99, 81, 93, 35]
sum = 0
for i in myList:
  sum = sum + i
print(f"정수들의 합은 {sum}입니다.")

# 3. 
sum = 0
for i in range(1, 101):
  if i%3 == 0:
    sum = sum + i 
  else:
    pass
print(f"1부터 100 사이의 모든 3의 배수의 합은 {sum}입니다.")

# 4. 
number = int(input("정수를 입력하시오: "))
for i in range(1, number+1):
  if number%i == 0:
    print(i, end = " ")

# 5. 답지 보고 푼 문제!
number = int(input("정수를 입력하시오: "))
for i in range(1, number+1):
  for x in range(1, i+1):
    print(x, end="")
  print()

# 6. 
import math
print("각도\t sin(x) \t cos(x)")
for angle in range(0, 91, 10):
  radian = 3.14 * (angle/180.0)
  sine = math.sin(radian)
  cosine = math.cos(radian)
  print(f"{angle:2d}\t{round(sine, 3):.4f}\t{round(cosine, 3):15f}")

# 8. 
n = 0
while n**2 <= 500:
  n += 1
  if n**2 > 500:
    break 
print(n)

# 9.
for i in range(1, 10):
  for x in range(1, 10):
    print(x * i, end = ' ')

# 10.
n = int(input("n의 값을 입력하시오: "))
sum = 0
for i in range(1, n+1):
  sum = sum + (i**2)
print(f"계산값은 {sum}입니다.")

# 11.
a = int(input("첫 번째 정수를 입력하세요: "))
b = int(input("두 번째 정수를 입력하세요: "))
m = min(a, b)
for i in range(1,  m+1):
  if a%m == 0 and b%m == 0:
    c = m 
print(f"{a}와 {b}의 최대 공약수는 {c}입니다.")

#13. 피보나치 수열 (답지 보고 풀었음)
number = int(input("몇 번째 항까지 구할까요?"))
n1, n2 = 0, 1
count = 0
while count <= number:
  print(n1, end=" ")
  nth = n1 + n2
  n1 = n2
  n2 = nth
  count += 1

#14.
n = 20
for i in range(n+1):
  result = True
  if i < 2:
    result = False
  for x in range(2, i):
    if i%x == 0:
      result = False
  if result:
    print(i)

#15.
sum = 0
for i in range(1, 100, 2):
  a = i + 2
  sum = sum + (i/a)
print(sum)

size = int(input("게임판의 크기"))
for i in range(size):
  print("---" * i, "|" * i, end = "\t")

for i in range(0, 10):
  if i%3 == 0 and i%5 == 0:
    print("fizzbuzz")
  elif i%3 == 0:
    print("fizz")
  elif i%5 == 0:
    print("buzz")
  else:
    print("*")

N = int(input("숫자를 입력하세요"))
n = N
cnt = 0
while True:
  a = n//10
  b = n%10
  c = (a + b) % 10
  n = (10*b) + c
  cnt += 1
  if n == N:
    break
print(cnt)