# -*- coding: utf-8 -*-
"""파워 유저를 위한 파이썬 - Chapter 5 함수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16pfscCBEMWR99Cuu296e3mauNo26ZRwk
"""

# 원의 넓이 구하는 함수
def get_area(radius):
  area = 3.14 * radius**2
  return area

area1 = get_area(6)
print(f"반지름이 6인 원의 면적은 {area1}입니다.")

# 피자 가성비 따지기 (내가 쓴 코드)
def get_area(radius):
  area = 3.14 * radius**2
  return area 
pizza1 = get_area(20)
pizza2 = get_area(30)
if (pizza1 * 2) > pizza2:
  print("20cm 피자 2판이 30cm 피자 1판보다 가성비가 좋습니다.")
else:
  print("30cm 피자 1판이 20cm 피자 2판보다 가성비가 좋습니다.")

# 피자 가성비 따지기 (책 코드)
def main() :
  print("20cm 피자 2개의 면적: ", get_area(20) + get_area(20))
  print("30cm 피자 1개의 면적: ", get_area(30))
def get_area(radius):
  if radius > 0:
    area = 3.14 * radius**2
  else:
    area = 0
  return area 
main()

def get_sum(start, end):
  sum = 0
  for i in range(start, end+1):
    sum += i
  return sum
value = get_sum(1, 10)
print(value)
x = get_sum(1, 100)
y = get_sum(1, 20)
print(x)
print(y)

def greet(name, msg="잘 가!"): #디폴트 인수 설정할 시 별도의 msg 값이 들어오지 않으면 디폴트 값을 출력
  print(f"안녕 {name}야, {msg}")
greet("철수", "좋은 아침!")
greet("영희")

def sub(x, y, z):
  print("x =", x, "y =", y, "z =", z)
sub(10, 20, 30)

def add(*numbers):
  sum = 0
  for n in numbers:
    sum = sum + n 
  return sum 
print(add(10, 20))
print(add(10, 20, 30))

def sum(a, b, c):
  print(a + b+ c)
alist = [1, 2, 3]
sum(*alist)

def display(msg="Welcome", count=1):
  for i in range(count):
    print(msg)
display("환영합니다", 5)

def weeklypay(rate, hour):
  if hour > 30:
    money = int((30 * rate) + ((hour-30) * (rate * 1.5)))
  else:
    money = int(rate * hour)
  return money
rate = int(input("시급을 입력하세요: "))
hour = int(input("근무 시간을 입력하세요: "))
print("주급은", weeklypay(rate, hour))

def addsub(x, y):
  sum = x + y
  subtract = abs(x - y)
  print(f"x와 y의 합은 {sum}입니다.")
  print(f"x와 y의 차는 {subtract}입니다.")
x = int(input())
y = int(input())
addsub(x, y)

def get_number():
  num1 = int(input("첫번째 정수를 입력하세요: "))
  num2 = int(input("두번째 정수를 입력하세요: "))
  return num1, num2
st_num1, st_num2 = get_number()
if st_num1 > st_num2:
  print(st_num1, st_num2)
else:
  print(st_num2, st_num1)

def menu():
  print("1. 섭씨 온도 -> 화씨 온도")
  print("2. 화씨 온도 -> 섭씨 온도")
  print("3. 종료")
  choice = int(input("메뉴를 선택하세요: "))
  return choice

def ctof(c):
  temp = c*(9.0/5.0) + 32
  return temp 

def ftoc(f):
  temp = (f-32) * 5.0/9.0
  return temp

def input_c():
  c = float(input("섭씨 온도를 입력하세요: ")) 
  return c

def input_f():
  f = float(input("화씨 온도를 입력하세요: "))
  return f

def main():
  while True:
    index = menu()
    if index == 1:
      t = input_c()
      t2 = ctof(t)
      print("화씨 온도= ", t2, "\n")
    elif index == 2:
      t = input_f()
      t2 = ftoc(t)
      print("섭씨 온도= ", t2, "\n")
    else:
      print("프로그램을 종료하였습니다.")
      break
      
main()

def factorial(n):
  if n == 1:
    return 1
  else:
    return n * factorial(n-1)

factorial(10)

def max(a, b):
  if a > b:
    result = a
  else:
    result = b
  return result

max(3, 5)

def main():
  print(mistery(10, 20))
def mistery(a, b):
  result = a
  if b < result:
    result = b 
  return result 
main()

def mistery(a, b, min):
  min = a
  if b < min:
    min = b

min = 0
mistery(20, 10, min)
print(min)

x = 10
def dec():
  global x 
  x = x - 1 
dec()
print(x)

#1. 
def get_peri(radius = 5.0):
  c = 2 * 3.14 * radius
  return c 
print(get_peri())
print(get_peri(4.0))

#2.
a = int(input("첫 번째 정수를 입력하세요: "))
b = int(input("두 번째 정수를 입력하세요: "))
def add(a, b):
  c = a + b
  return c
def subtract(a, b):
  c = a - b 
  return c
def multiple(a, b):
  c = a * b
  return c 
def division(a, b):
  c = a / b 
  return c
print(f"{a} + {b} = ", add(a, b))  
print(f"{a} - {b} = ", subtract(a, b))  
print(f"{a} * {b} = ", multiple(a, b))  
print(f"{a} / {b} = ", division(a, b))

#3. 
a = int(input("첫 번째 정수를 입력하세요: "))
b = int(input("두 번째 정수를 입력하세요: "))
def add(a, b):
  c = a + b
  return c
def subtract(a, b):
  c = a - b 
  return c
def multiple(a, b):
  c = a * b
  return c 
def division(a, b):
  c = a / b 
  return c
def calc():
  return add(a, b), subtract(a, b), multiple(a, b), division(a, b)
print(calc(), "이 반환되었습니다.")

#3 - 답지 답안
def calc(a, b):
  return a+b, a-b, a*b, a/b 

x = int(input("첫 번째 정수를 입력하세요: "))
y = int(input("두 번째 정수를 입력하세요: "))
a, b, c, d = calc(x, y)
print(a, b, c, d, "가 반환되었습니다.")

def getGrade(score):
  score = int(input("점수를 입력하세요: "))
  if score >= 90:
    return "A"
  elif 90 > score >= 80:
    return "B"
  elif 80 > score >= 70:
    return "C"
  elif 70 > score >= 60:
    return "D"
  else:
    return "F"
print("성적은", getGrade(score), "입니다.")

p = input("패스워드를 입력하시오: ")
def checkPass(p):
  digit, lower, upper = 0, 0, 0
  for i in p:
    if p.islower():
      lower >= 1
    elif p.isupper():
      upper >= 1
    elif p.isdigit():
      digit >= 1
  if len(p) >= 8 and upper and lower and digit: 
    print("사용할 수 있습니다.")
  else: 
    print("사용할 수 없습니다.")
checkPass(p)

def question(a, b):
  print("정수", a, "+", b, "의 합은?")
num1 = int(input("첫 번째 정수를 입력하세요: "))
num2 = int(input("두 번째 정수를 입력하세요: "))
x = question(num1, num2)

#7.
print("날짜를 입력하세요(월과 일)")
def getIntRange(a, b, msg):
  x = -100
  while x < a or x > b:
    x = int(input(msg))
  return x
m = getIntRange(1, 12, "월을 입력하세요(1부터 12 사이의 값): ")
d = getIntRange(1, 31, "일을 입력하세요(1부터 31 사이의 값): ")
print(f"입력된 날짜는 {m}월 {d}일입니다.")

#8.

#9. 
def denominator(a, b):
  m = min(a, b)
  for i in range(1, m+1):
    if a%m == 0 and b%m == 0:
      c = m
  return c 
a = int(input("첫 번째 정수: "))
b = int(input("두 번째 정수: "))
print(denominator(a, b))

#10. 
def prime(n):
  for i in range(n+1):
    result = True
    if i < 2:
      result = False
    for x in range(2, i):
      if i%x == 0:
        result = False
    if result:
      print(i)
prime(100)

#11. 내가 쓴 답
def deci2bin(n):
  n = bin(n)
  return n
x = int(input("10진수: "))
deci2bin(x)

#11 - 1
def deci2bin(n):
  binary = ""
  while n != 0:
    value = n % 2
    if value == 0:
      binary = "0" + binary
    else:
      binary = "1" + binary
    n = n // 2
  return binary
x = int(input("10진수: "))
print(deci2bin(x))

#12.
def getSorted():
  x = int(input("첫 번째 정수: "))
  y = int(input("두 번째 정수: "))
  if x > y:
    return x, y 
  else:
    return y, x 
getSorted()

#13.
import random 
def dicegame():  
  print("======== dice_game() 호출 ========")
  human = random.randint(1, 6)
  print("인간: 주사위값 = ", human)
  robot = random.randint(1, 6)
  print("컴퓨터: 주사위값 = ", robot) 
  h = human
  r = robot
  if h > r:
    print("인간승리")
  elif h < r:
    print("컴퓨터승리")
  else:
    print("무승부")
  print("========= dice_game() 복귀 ========")

def main():
  while True:
    dicegame()
    user = input("중단할까요? Y/N")
    if user == "Y" or user == "y":
      break
main()

import math
def formula(x, y):
  x = 2
  y = 1
  g = y
  num1 = float(x/g)
  print(num1)
  if abs(num1) == y:
    print(g)
  else:
    k = ((num1) + g)/2
    print(k)
formula(2, 1.4167)